### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Lufou** [Leafgard/mtxserv-node#18]
Décrit sur Discord, refresh du token toutes les 10 minutes, l'erreur n'est pas fatale.
En appelant checkserver() qui permet de retrieve les infos de mon serveur, cela génère cette erreur :

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at mTxRequest.request (/root/luvinsastroibot/node_modules/mtxserv-node/src/mTxRequest.js:51:82)
    at Viewer.getGameServerData (/root/luvinsastroibot/node_modules/mtxserv-node/src/Viewer/index.js:26:28)
    at Timeout.checkserver [as _onTimeout] (/root/luvinsastroibot/LuvinsaStroiBot.js:103:41)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
```

```
  at Timeout.checkserver [as _onTimeout] (/root/luvinsastroibot/LuvinsaStroiBot.js:103:41)
```

correspond à :
```js
let connection = mTxServ_client.Viewer.getGameServerData('garry-s-mod', '149.202.237.229', '27240');
```

**Comment by Leafgard** [comment]
Pourrais-je avoir un bout de code ?
Je ne peux pas deviner ce que vous souhaitez faire.
Par habitude, je dirais que c'est un problème au niveau des tokens d'authentification !

Par ailleurs, je vois que vous commencez sur GitHub, je vous invite donc à lire ce [petit post](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f) :)

**Comment by Lufou** [comment]
Pas reproductible, les debugs ne sont pas concluante, plus rien à signaler.
